import { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Camera, Image as ImageIcon, Upload, RefreshCcw, AlertTriangle } from 'lucide-react';
import './App.css';

const API_URL = '/predict';

const MUDRA_INFO = {
  "Alapadma": "Fully bloomed lotus; beauty, purity, fullness.",
  "Araala": "Bent finger; drinking poison, wind, unsteadiness.",
  "Ardhachandra": "Half moon; moon, female, spear.",
  "Ardhapataka": "Half flag; leaves, knives, separation.",
  "Chandrakala": "Crescent moon; moon, ornament, tenderness.",
  "Kartarimukha": "Scissors face; separation, opposition, lightning.",
  "Mayura": "Peacock; purity, bird, applying kajal.",
  "Mrigashirsha": "Deer head; woman's cheek, searching, calling.",
  "Mushti": "Fist; strength, holding, anger.",
  "Padmakosha": "Lotus bud; fruits, balls, breast.",
  "Pataka": "Flag; cloud, forest, denial, wind.",
  "Sarpashirsha": "Serpent head; snake, water offering.",
  "Shikhara": "Peak; bow, determination, valor.",
  "Simhamukha": "Lion face; courage, strength, ferocity.",
  "Suchi": "Needle; indication, number one, pointing.",
  "Tripataka": "Three-part flag; crown, tree, arrow.",
  "Trishula": "Trident; trinity, weapon of Shiva."
};

function App() {
  const [mode, setMode] = useState('upload'); // 'upload' or 'camera'
  const [targetMudra, setTargetMudra] = useState('');
  const [imageSrc, setImageSrc] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  const videoRef = useRef(null);
  const streamRef = useRef(null);
  const fileInputRef = useRef(null);

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "user" }
      });
      videoRef.current.srcObject = stream;
      streamRef.current = stream;
    } catch (err) {
      console.error("Error accessing camera:", err);
      alert("Could not access camera. Please check permissions.");
    }
  };

  const stopCamera = () => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop());
      streamRef.current = null;
    }
  };

  const handleModeChange = (newMode) => {
    if (newMode === 'camera') {
      setImageSrc(null);
      setResult(null);
      startCamera();
    } else {
      stopCamera();
    }
    setMode(newMode);
  };

  const captureImage = () => {
    if (!videoRef.current) return;
    const canvas = document.createElement('canvas');
    canvas.width = videoRef.current.videoWidth;
    canvas.height = videoRef.current.videoHeight;
    const ctx = canvas.getContext('2d');
    // Mirror the image correctly before capturing
    ctx.translate(canvas.width, 0);
    ctx.scale(-1, 1);
    ctx.drawImage(videoRef.current, 0, 0);

    canvas.toBlob((blob) => {
      stopCamera(); // Release camera access 
      setImageSrc(URL.createObjectURL(blob));
      predictImage(blob);
    }, 'image/jpeg', 0.9);
  };

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const url = URL.createObjectURL(file);
    setImageSrc(url);
    predictImage(file);
  };

  const predictImage = async (imageBlob) => {
    setLoading(true);
    setResult(null);

    const formData = new FormData();
    formData.append('file', imageBlob, 'capture.jpg');
    if (targetMudra) {
      formData.append('target_mudra', targetMudra);
    }

    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        body: formData,
      });
      const data = await response.json();
      setResult(data);
      if (data.cropped_image) {
        setImageSrc(data.cropped_image);
      }

      // Auto-play the advanced NLP voice stream generated by Python gTTS
      if (data.audio_url) {
        const audio = new Audio(data.audio_url);
        audio.play().catch(e => console.error("Audio playback failed (browser auto-play policy):", e));
      }
    } catch (err) {
      console.error(err);
      setResult({ success: false, error: 'network_error', message: 'Failed to connect to inference server. Ensure backend is running.' });
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setImageSrc(null);
    setResult(null);
    if (mode === 'camera') startCamera();
  };

  return (
    <div className="app-container">
      <header className="header">
        <motion.h1
          className="title"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          NrityaVaani
        </motion.h1>
        <motion.p
          className="subtitle"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
        >
          Live Bharatanatyam Mudra Recognition powered by artificial intelligence.
        </motion.p>
      </header>

      <main className="main-content">
        <section className="input-section glass-panel">

          <div className="mode-toggle">
            <button
              className={`toggle-btn ${mode === 'upload' ? 'active' : ''}`}
              onClick={() => handleModeChange('upload')}
            >
              <ImageIcon size={18} /> Upload
            </button>
            <button
              className={`toggle-btn ${mode === 'camera' ? 'active' : ''}`}
              onClick={() => handleModeChange('camera')}
            >
              <Camera size={18} /> Camera
            </button>
          </div>

          {mode === 'camera' && !imageSrc && (
            <div className="practice-selector">
              <label htmlFor="mudra-select">Practice Target:</label>
              <select
                id="mudra-select"
                value={targetMudra}
                onChange={(e) => setTargetMudra(e.target.value)}
                className="mudra-dropdown"
              >
                <option value="">None (Free Capture)</option>
                {['Alapadma', 'Ardhapataka', 'Chandrakala', 'Kartarimukha', 'Mayura', 'Pataka', 'Shikhara', 'Simhamukha', 'Suchi', 'Tripataka'].map((mudra) => (
                  <option key={mudra} value={mudra}>{mudra} - Trained</option>
                ))}
              </select>
            </div>
          )}

          <div style={{ padding: '0 2rem 2rem 2rem' }}>
            <AnimatePresence mode="wait">

              {!imageSrc && mode === 'upload' && (
                <motion.div
                  key="upload"
                  className="upload-area"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  onClick={() => fileInputRef.current?.click()}
                  whileHover={{ scale: 1.02 }}
                >
                  <Upload className="upload-icon" />
                  <h3>Drop your image here</h3>
                  <p style={{ color: 'var(--text-muted)' }}>Supports JPG, PNG</p>
                  <input
                    type="file"
                    ref={fileInputRef}
                    className="hidden-input"
                    accept="image/*"
                    onChange={handleFileUpload}
                  />
                </motion.div>
              )}

              {!imageSrc && mode === 'camera' && (
                <motion.div
                  key="camera"
                  className="camera-layout"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                >
                  <div className="video-container main-camera">
                    <video
                      ref={videoRef}
                      autoPlay
                      playsInline
                      className="video-feed"
                    />
                    <div className="camera-controls">
                      <button className="btn-primary" onClick={captureImage}>
                        <Camera size={20} /> Capture Mudra
                      </button>
                    </div>
                  </div>

                  {targetMudra && (
                    <div className="practice-target-container">
                      <h3 className="practice-label-top">Practice Goal</h3>
                      <img src={`/mudras/${targetMudra}.jpg`} alt={targetMudra} className="practice-img-large" onError={(e) => { e.target.style.display = 'none'; }} />
                      <p className="practice-desc">{MUDRA_INFO[targetMudra]}</p>
                    </div>
                  )}
                </motion.div>
              )}

              {imageSrc && (
                <motion.div
                  key="preview"
                  className="preview-container"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                >
                  <img src={imageSrc} alt="Captured" className="preview-image" />
                  <div className="camera-controls">
                    <button className="btn-secondary" onClick={reset}>
                      <RefreshCcw size={18} /> Try Another
                    </button>
                  </div>
                </motion.div>
              )}

            </AnimatePresence>
          </div>
        </section>

        <section className="result-section">
          {loading && (
            <motion.div
              className="glass-panel result-card"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '300px' }}
            >
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
                style={{ borderRadius: '50%', border: '3px solid var(--border-highlight)', borderTopColor: 'var(--accent-primary)', width: '40px', height: '40px' }}
              />
              <p style={{ marginLeft: '1rem', color: 'var(--text-secondary)' }}>Analyzing Mudra with MediaPipe...</p>
            </motion.div>
          )}

          {!loading && result && (
            <motion.div
              className="glass-panel result-card"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
            >
              {result.success ? (
                <>
                  <div className="result-header">
                    <h2>{result.mudra}</h2>
                    <div className="mudra-comparison">
                      <div className="mudra-image-container">
                        <span className="image-label">Your Capture (Cropped)</span>
                        <img src={result.cropped_image || imageSrc} alt="Your input" className="comparison-img" />
                      </div>
                      <div className="mudra-image-container">
                        <span className="image-label">Reference Mudra</span>
                        <img src={`/mudras/${result.mudra}.jpg`} alt={result.mudra} className="comparison-img" onError={(e) => { e.target.style.display = 'none'; }} />
                      </div>
                    </div>
                  </div>

                  <div className="info-section">
                    <span className="info-label">Confidence Score</span>
                    <span className="info-value" style={{ color: 'var(--success)', fontWeight: 'bold' }}>
                      {result.confidence}%
                    </span>
                    <div className="confidence-meter">
                      <motion.div
                        className="confidence-fill"
                        initial={{ width: 0 }}
                        animate={{ width: `${result.confidence}%` }}
                      />
                    </div>
                  </div>

                  <div className="info-section" style={{ marginTop: '1rem' }}>
                    <span className="info-label">Classical Meaning (Database)</span>
                    <span className="info-value">
                      {MUDRA_INFO[result.mudra] || "Meaning not available in current database."}
                    </span>
                  </div>

                  {result.gemini_message && (
                    <div className="info-section" style={{ marginTop: '1rem', background: 'rgba(var(--accent-primary-rgb), 0.1)', borderColor: 'var(--accent-primary)' }}>
                      <span className="info-label" style={{ color: 'var(--accent-primary)' }}>✨ Gemini AI Insight</span>
                      <span className="info-value" style={{ fontStyle: 'italic' }}>
                        "{result.gemini_message}"
                      </span>
                    </div>
                  )}
                </>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', alignItems: 'center', textAlign: 'center', padding: '2rem 0' }}>
                  <AlertTriangle size={48} color="var(--warning)" />
                  <h3>Inference Warning</h3>
                  <p style={{ color: 'var(--text-secondary)' }}>{result.message}</p>

                  {result.mudra && (
                    <div style={{ width: '100%', marginTop: '1rem' }}>
                      <div className="mudra-comparison">
                        <div className="mudra-image-container">
                          <span className="image-label">Your Capture (Cropped)</span>
                          <img src={result.cropped_image || imageSrc} alt="Your input" className="comparison-img" />
                        </div>
                        <div className="mudra-image-container">
                          <span className="image-label">Reference Mudra</span>
                          <img src={`/mudras/${result.mudra}.jpg`} alt={result.mudra} className="comparison-img" onError={(e) => { e.target.style.display = 'none'; }} />
                        </div>
                      </div>
                      <div className="info-section" style={{ marginTop: '2rem', textAlign: 'center' }}>
                        <span className="info-label">Predicted (Low Confidence)</span>
                        <span className="info-value">{result.mudra} ({result.confidence}%)</span>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </motion.div>
          )}

          {!loading && !result && (
            <div className="glass-panel" style={{ height: '300px', display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.5 }}>
              <p>Upload or capture an image to see predictions.</p>
            </div>
          )}
        </section>
      </main>

      <section className="encyclopedia">
        <h2>Mudra Library</h2>
        <div className="mudra-grid">
          {Object.entries(MUDRA_INFO).map(([mudra, meaning], idx) => (
            <motion.div
              key={mudra}
              className="glass-panel mudra-card"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.05 }}
            >
              <img src={`/mudras/${mudra}.jpg`} alt={mudra} className="encyclopedia-img" onError={(e) => { e.target.style.display = 'none'; }} />
              <h3>{mudra}</h3>
              <p>{meaning}</p>
            </motion.div>
          ))}
        </div>
      </section>

    </div>
  );
}

export default App;
